<?php 
    $estados =
    [
        'estados' => [
            0 => [
                'sigla' => 'RS',
                'cidades' => [
                    0 => 'Rio Grande',
                    1 => 'Pelotas',
                    2 => 'Aceguá',
                    3 => 'Água Santa',
                    4 => 'Agudo',
                    5 => 'Ajuricaba',
                    6 => 'Alecrim',
                    7 => 'Alegrete',
                    8 => 'Alegria',
                    9 => 'Almirante Tamandaré do Sul',
                    10 => 'Alpestre',
                    11 => 'Alto Alegre',
                    12 => 'Alto Feliz',
                    13 => 'Alvorada',
                    14 => 'Amaral Ferrador',
                    15 => 'Ametista do Sul',
                    16 => 'André da Rocha',
                    17 => 'Anta Gorda',
                    18 => 'Antônio Prado',
                    19 => 'Arambaré',
                    20 => 'Araricá',
                    21 => 'Aratiba',
                ],
            ],
            1 => [
                'sigla' => 'SP',
                'cidades' => [
                    0 => 'Adamantina',
                    1 => 'Adolfo',
                    2 => 'Aguaí',
                    3 => 'Águas da Prata',
                    4 => 'Águas de Lindóia',
                    5 => 'Águas de Santa Bárbara',
                    6 => 'Águas de São Pedro',
                    7 => 'Agudos',
                    8 => 'Alambari',
                    9 => 'Alfredo Marcondes',
                    10 => 'Altair',
                    11 => 'Altinópolis',
                    12 => 'Alto Alegre',
                    13 => 'Alumínio',
                    14 => 'Álvares Florence',
                    15 => 'Álvares Machado',
                    16 => 'Álvaro de Carvalho',
                    17 => 'Alvinlândia',
                    18 => 'Americana',
                    19 => 'Américo Brasiliense',
                    20 => 'Américo de Campos',
                    21 => 'Amparo',
                    22 => 'Analândia',
                    23 => 'Andradina',
                    24 => 'Angatuba',
                    25 => 'Anhembi',
                ],
            ],
            2 => [
                'sigla' => 'SC',
                'cidades' => [
                    0 => 'Abdon Batista',
                    1 => 'Abelardo Luz',
                    2 => 'Agrolândia',
                    3 => 'Agronômica',
                    4 => 'Água Doce',
                    5 => 'Águas de Chapecó',
                    6 => 'Águas Frias',
                    7 => 'Águas Mornas',
                    8 => 'Alfredo Wagner',
                    9 => 'Alto Bela Vista',
                    10 => 'Anchieta',
                    11 => 'Angelina',
                    12 => 'Anita Garibaldi',
                    13 => 'Anitápolis',
                    14 => 'Antônio Carlos',
                    15 => 'Apiúna',
                    16 => 'Arabutã',
                    17 => 'Araquari',
                    18 => 'Araranguá',
                ],
            ],
        ],
    ];
    
    echo json_encode($estados);
    
?>